### ISSUE TITLE
Double clicking dss file in windows explorer breaks installation

### ISSUE THREAD

**Issue by faph** [EnviroCentre/jython-upgrade#2]
After installing the java/jython upgrade, the HEC-DSSVue java environment may get corrupted when you open HEC-DSSVue by double clicking a dss file in Windows Explorer. This is something to do with the .dss file association.

Opening the dss file from within HEC-DSSVue works fine.

TODO: fix dss file association.

**Comment by faph** [comment]
Dump of windows registry:

``` ini
[HKEY_CLASSES_ROOT\dssfile\shell\Open\command]
@="\"C:\\Program Files (x86)\\HEC\\HEC-DSSVue\\HEC-DSSVue.exe\" \"%1\""
"command"=hex(7):59,00,61,00,4e,00,2d,00,67,00,24,00,55,00,31,00,21,00,41,00,\
  7b,00,76,00,36,00,69,00,54,00,4e,00,4b,00,2c,00,73,00,68,00,4d,00,61,00,69,\
  00,6e,00,41,00,70,00,70,00,6c,00,69,00,63,00,61,00,74,00,69,00,6f,00,6e,00,\
  3e,00,45,00,6f,00,4b,00,26,00,4d,00,34,00,5f,00,4c,00,69,00,38,00,5e,00,46,\
  00,3f,00,60,00,5f,00,61,00,6a,00,31,00,4e,00,47,00,20,00,22,00,25,00,31,00,\
  22,00,00,00,00,00
```

The `command` value seems spurious/superfluous?

**Comment by faph** [comment]
Seems so. We need to delete the `command` value.

**Comment by faph** [comment]
Fixed by ff64f24e66ee1281d55dbf777c2b057acc60e9b7.

**Comment by jprine** [comment]
Did this bug produce the error: "HEC-DSSVue has closed in an unexpected way. ... Java returned the following error code: 1". Nothing is written out to the log, but in the Console I got:

```
error occurred during initialization of vm 
java/lang/noclassdeffounderror java/lang/invoke/methodhandle
```

I just re-installed the Jython upgrade and it seems to be working again, but I want to make sure it wasn't some other bug.

**Comment by faph** [comment]
I think that's correct. We've not come across other issues.
